# Database connection - bruger miljøvariabler på Azure, ellers localhost
spring.datasource.url=${68.221.170.167:3306/wishlist_db}
spring.datasource.username=${JDBC_USERNAME:admin}
spring.datasource.password=${JDBC_PASSWORD:1234}

# Driver class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Kør schema.sql og data.sql ved opstart
spring.sql.init.mode=never

# Slå Thymeleaf cache fra under udvikling
spring.thymeleaf.cache=false