# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/wishlist_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=igor

# Kør schema.sql og data.sql ved opstart
spring.sql.init.mode=always

# Slå Thymeleaf cache fra under udvikling (så du ikke behøver genstarte ved HTML-ændringer)
spring.thymeleaf.cache=false